---
- name: Install Docker
  become: true
  hosts: localhost

  tasks:
    - name: Install dependencies
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: latest
    - name: Adding repositories
      command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
    - name: Install Docker
      ansible.builtin.dnf: 
        name: "{{ item }}"
        state: latest
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io 
        - docker-compose-plugin


    - name: Set up user permssion for docker
      command: groupadd docker
      command: usermod -aG docker $USER



