---
- name: Install Brave Browser
  become: true
  hosts: localhost

  tasks:
    - name: Adding repository
      command: sudo dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/

    - name: Adding rpm key
      ansible.builtin.rpm_key:
        state: present
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

    - name: Install Brave
      ansible.builtin.dnf:
        name: brave-browser
        state: latest

